name: cybersec-recsys
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=2.0,<3.0
  - pandas>=2.2.2,<3.0
  - scipy>=1.13,<2.0
  - scikit-learn>=1.7,<1.8
  - jupyterlab>=4
  - ipykernel>=6.29
  - matplotlib>=3.8,<4.0
  - seaborn>=0.13
  - pip
  - pip:
      - tensorflow==2.19.0
      - streamlit==1.48.0
      - python-dotenv>=1.0
      - tqdm>=4.66
      - networkx>=3.3
      - rich>=13
      - pytest>=8
